### ISSUE TITLE
Error while trying to run the OpenMM simulation

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/SimuMole#83]
`Requested periodic boundary conditions for a Topology that does not specify periodic box dimensions`

While trying to run a python file created by the OpenMM script builder, that can be found here: 
https://github.com/TechnionYP5779/SimuMole/blob/run_simulation_brunch/src/SimuMole/media/files/openmm.py

with the a .pbp file named "both__pdb_1__6DY4__movement_pdb_2__5ZKH__movement.pdb",
that can be found here:
https://github.com/TechnionYP5779/SimuMole/blob/run_simulation_brunch/src/SimuMole/media/files/both__pdb_1__6DY4__movement_pdb_2__5ZKH__movement.pdb

The same happened to me with another 2 molecules (6DY4 twice)
Please help.

To run the script simply run "python openmm.py" in a folder with both the script and the pdb file specified above.

**Comment by IlanitSmul** [comment]
**in `openmm.py`, line 10:** 
`system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.PME, `

The problem is caused by the `nonbondedMethod=app.PME` parameter. 
Try replacing it with `nonbondedMethod=app.NoCutoff`.

This change fixes the error you specified, but there are still other errors about the rest of the code - so you probably have to check which parameters can be replaced.

**Comment by HadadIdan** [comment]
Thanks both @IlanitSmul and @MichaelShohat I have found settings that allow for a working simultaion, and they can be seen on https://github.com/TechnionYP5779/SimuMole/tree/run_simulation_brunch .
Changing the nonboundedMethod did help as Ilanit suggested, but there were other changed that allowed it to work. We are now using a different, basic openMM script builder.
